(()=>{
const canvas=document.querySelector('#game'),ctx=canvas.getContext('2d');
const $=s=>document.querySelector(s);
const roster=[
{id:'akira',name:'明良',country:'日本',flag:'🇯🇵',style:'风拳 · 气波',color:'#e55258',dark:'#652830',skin:'#f3c49a',special:'wave'},
{id:'lin',name:'林月',country:'中国',flag:'🇨🇳',style:'飞踢 · 气旋',color:'#46bac4',dark:'#175269',skin:'#eebd91',special:'spin'},
{id:'mason',name:'梅森',country:'美国',flag:'🇺🇸',style:'重拳 · 突进',color:'#557bdc',dark:'#263f7d',skin:'#9e654b',special:'dash'},
{id:'bruno',name:'布鲁诺',country:'德国',flag:'🇩🇪',style:'铁拳 · 震地',color:'#e2a746',dark:'#76522e',skin:'#e9bd9c',special:'quake'}];
const inputs=new Set(),pressed=new Set(),keys={a:'left',d:'right',w:'jump',s:'block',j:'light',k:'heavy',l:'special',ArrowLeft:'left',ArrowRight:'right',ArrowUp:'jump',ArrowDown:'block'};
let selected=0,p=null,e=null,projectiles=[],effects=[],mode='menu',timer=60,round=1,wins=[0,0],last=0,aiClock=0,transition=0,bannerTime=0,bannerText='',clock=0;
const ground=445;
function rosterUI(){ $('#roster').innerHTML=roster.map((r,i)=>'<button class="card '+(i===selected?'selected':'')+'" data-id="'+i+'"><span class="flag">'+r.flag+'</span><strong>'+r.name+'</strong><small>'+r.country+' · '+r.style+'</small></button>').join('');}
rosterUI();
$('#roster').addEventListener('click',ev=>{const card=ev.target.closest('[data-id]');if(card){selected=Number(card.dataset.id);rosterUI();}});
function fighter(type,x,face){return {type,x,y:ground,vx:0,vy:0,face,hp:100,energy:0,stun:0,attack:null,attackAge:0,cool:0,block:false,inv:0,flash:0,hitDone:false};}
function resetRound(){p=fighter(roster[selected],240,1);let rival=(selected+1+(round-1)%3)%4;e=fighter(roster[rival],720,-1);projectiles=[];effects=[];timer=60;aiClock=0;mode='fight';banner('回合 '+round,1.1);updateHud();}
function start(){wins=[0,0];round=1;$('#overlay').hidden=true;resetRound();last=performance.now();}
$('#start').addEventListener('click',start);
function banner(s,t){bannerText=s;bannerTime=t;$('#banner').textContent=s;$('#banner').hidden=false;}
function down(k){if(!inputs.has(k))pressed.add(k);inputs.add(k);}
function up(k){inputs.delete(k);}
addEventListener('keydown',ev=>{let k=keys[ev.key];if(k){ev.preventDefault();down(k);}if(ev.key==='Enter'&&!$('#overlay').hidden)start();});
addEventListener('keyup',ev=>{let k=keys[ev.key];if(k){ev.preventDefault();up(k);}});
addEventListener('blur',()=>{inputs.clear();pressed.clear();});
for(const button of document.querySelectorAll('.controls button')){const k=button.dataset.key;button.addEventListener('pointerdown',ev=>{ev.preventDefault();button.setPointerCapture(ev.pointerId);button.classList.add('pressed');down(k);});for(const event of ['pointerup','pointercancel','lostpointercapture'])button.addEventListener(event,()=>{button.classList.remove('pressed');up(k);});}
function effect(x,y,color,n=12){for(let i=0;i<n;i++){let a=Math.random()*Math.PI*2,s=70+Math.random()*180;effects.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,life:.3+Math.random()*.25,color});}}
function beginAttack(f,kind){if(f.cool>0||f.stun>0||f.attack||mode!=='fight')return;let cfg={light:[.28,.37],heavy:[.45,.7],special:[.58,1.15]}[kind];if(kind==='special'&&f.energy<35)return;f.attack=kind;f.attackAge=0;f.hitDone=false;f.cool=cfg[1];if(kind==='special'){f.energy-=35;if(f.type.special==='wave')projectiles.push({x:f.x+f.face*36,y:f.y-88,vx:f.face*440,owner:f,life:1.4,color:'#71dcff'});if(f.type.special==='dash')f.vx=f.face*600;if(f.type.special==='quake')effect(f.x,f.y-8,'#f4be69',24);} }
function strike(f,target,kind){let reach=kind==='light'?88:kind==='heavy'?112:kind==='special'?(f.type.special==='quake'?160:115):85;let close=Math.abs(target.x-f.x)<reach&&Math.abs(target.y-f.y)<85&&Math.sign(target.x-f.x)===f.face;if(!close)return;let damage=kind==='light'?7:kind==='heavy'?14:kind==='special'?19:9;hit(target,damage,f,kind);}
function hit(target,damage,source,kind){if(target.inv>0||mode!=='fight')return;let guarding=target.block&&target.y===ground&&target.face===-source.face;let dealt=guarding?Math.ceil(damage*.22):damage;target.hp=Math.max(0,target.hp-dealt);target.energy=Math.min(100,target.energy+(guarding?4:8));source.energy=Math.min(100,source.energy+(guarding?2:kind==='light'?7:11));target.stun=guarding?.1:.25;target.inv=.12;target.flash=.16;target.vx+=source.face*(guarding?65:kind==='heavy'?290:180);effect(target.x,target.y-90,guarding?'#8ad5ff':'#ffdf75',guarding?6:15);updateHud();if(target.hp<=0)finishRound(source===p?0:1);}
function finishRound(winner){if(mode!=='fight')return;mode='between';wins[winner]++;banner(winner===0?'你赢了！':'对手胜利',1.6);transition=2;if(wins[winner]===2){mode='over';transition=1.8;}}
function updateHud(){if(!p||!e)return;$('#p-name').textContent=p.type.flag+' '+p.type.name+' '+wins[0]+'胜';$('#e-name').textContent=wins[1]+'胜 '+e.type.name+' '+e.type.flag;$('#p-health').style.width=p.hp+'%';$('#e-health').style.width=e.hp+'%';$('#p-energy').style.width=p.energy+'%';$('#e-energy').style.width=e.energy+'%';$('#timer').textContent=Math.ceil(timer);$('#round-label').textContent='第 '+round+' 回合';}
function controls(f,move,jump,block,attacks,dt){if(f.stun>0){f.block=false;return;}f.block=block&&!f.attack&&f.y===ground;f.face=f===p?(e.x>=f.x?1:-1):(p.x>=f.x?1:-1);if(!f.block&&!f.attack){f.vx+=move*1650*dt;f.vx=Math.max(-300,Math.min(300,f.vx));if(jump&&f.y>=ground){f.vy=-690;f.y=ground-1;}}for(const kind of attacks)beginAttack(f,kind);}
function ai(dt){aiClock-=dt;let move=0,jump=false,block=false,attacks=[];const d=p.x-e.x,range=Math.abs(d);if(aiClock<=0){aiClock=.18+Math.random()*.16;e.intent=range>110?Math.sign(d):range<65?-Math.sign(d):0;e.guard=Math.random()<.32;}move=e.intent||0;block=e.guard&&range<125&&!!p.attack&&p.attackAge<.22;if(range<95&&Math.random()<dt*2.5)attacks.push('light');if(range<125&&Math.random()<dt*1.3)attacks.push('heavy');if(e.energy>=35&&range<160&&Math.random()<dt*.8)attacks.push('special');if(range>170&&Math.random()<dt*.15)jump=true;controls(e,move,jump,block,attacks,dt);}
function updateFighter(f,target,dt){f.stun=Math.max(0,f.stun-dt);f.cool=Math.max(0,f.cool-dt);f.inv=Math.max(0,f.inv-dt);f.flash=Math.max(0,f.flash-dt);f.vy+=1700*dt;f.y+=f.vy*dt;if(f.y>=ground){f.y=ground;f.vy=0;}f.x+=f.vx*dt;f.vx*=Math.pow(f.y===ground?.055:.5,dt);f.x=Math.max(55,Math.min(905,f.x));if(f.attack){f.attackAge+=dt;let active=f.attack==='light'?.11:f.attack==='heavy'?.19:.16;if(!f.hitDone&&f.attackAge>=active){f.hitDone=true;if(f.attack!=='special'||f.type.special!=='wave')strike(f,target,f.attack);if(f.attack==='special'&&f.type.special==='spin')strike(f,target,'special');}if(f.attackAge>(f.attack==='light'?.28:f.attack==='heavy'?.45:.58))f.attack=null;}}
function update(dt){clock+=dt;if(bannerTime>0){bannerTime-=dt;if(bannerTime<=0)$('#banner').hidden=true;}if(mode==='between'||mode==='over'){transition-=dt;if(transition<=0){if(mode==='over'){showResult();}else{round++;resetRound();}}return;}if(mode!=='fight')return;timer-=dt;if(timer<=0){timer=0;finishRound(p.hp>=e.hp?0:1);}let move=Number(inputs.has('right'))-Number(inputs.has('left'));controls(p,move,pressed.has('jump'),inputs.has('block'),['light','heavy','special'].filter(k=>pressed.has(k)),dt);ai(dt);pressed.clear();updateFighter(p,e,dt);updateFighter(e,p,dt);if(Math.abs(p.x-e.x)<70){let mid=(p.x+e.x)/2;p.x=mid-35;e.x=mid+35;}for(const shot of projectiles){shot.x+=shot.vx*dt;shot.life-=dt;let target=shot.owner===p?e:p;if(shot.life>0&&Math.abs(shot.x-target.x)<38&&Math.abs(shot.y-(target.y-88))<65){shot.life=0;hit(target,17,shot.owner,'special');}}projectiles=projectiles.filter(s=>s.life>0&&s.x>0&&s.x<960);for(const fx of effects){fx.x+=fx.vx*dt;fx.y+=fx.vy*dt;fx.life-=dt;}effects=effects.filter(x=>x.life>0);updateHud();}
function showResult(){$('#menu-title').textContent=wins[0]>=2?'挑战成功！':'挑战结束';$('#menu-text').textContent=wins[0]>=2?'你赢下了这场三局两胜的对战。选择斗士，再挑战一次！':'电脑对手赢了。换一位斗士，再来一场！';$('#start').textContent='再战一场';$('#overlay').hidden=false;mode='menu';}
function drawStage(){let sky=ctx.createLinearGradient(0,0,0,540);sky.addColorStop(0,'#171d3e');sky.addColorStop(.68,'#6d5672');sky.addColorStop(1,'#b17662');ctx.fillStyle=sky;ctx.fillRect(0,0,960,540);ctx.fillStyle='#eebc8d';ctx.beginPath();ctx.arc(750,142,61,0,7);ctx.fill();for(let layer=0;layer<2;layer++){ctx.fillStyle=layer?'#343957':'#4c4865';let base=layer?350:300;for(let x=-30;x<1000;x+=65){let h=40+((x*17+layer*89)%85);ctx.fillRect(x,base-h,52,h+170);for(let y=base-h+12;y<base;y+=18){ctx.fillStyle=layer?'#8d7891':'#cf938e';ctx.fillRect(x+8,y,5,6);ctx.fillRect(x+28,y,5,6);ctx.fillStyle=layer?'#343957':'#4c4865';}}}ctx.fillStyle='#303b43';ctx.fillRect(0,ground,960,95);ctx.fillStyle='#d49e66';ctx.fillRect(0,ground,960,10);ctx.strokeStyle='#6d7070';ctx.lineWidth=2;for(let x=-60;x<1020;x+=120){ctx.beginPath();ctx.moveTo(x,540);ctx.lineTo(x+80,ground+10);ctx.stroke();}}
function drawFighter(f){if(!f)return;ctx.save();ctx.translate(f.x,f.y);ctx.scale(f.face,1);let bob=f.y===ground?Math.sin(clock*7)*2:0;ctx.translate(0,bob);ctx.globalAlpha=f.inv>0&&Math.floor(clock*24)%2===0?.55:1;ctx.fillStyle='#161b26aa';ctx.beginPath();ctx.ellipse(0,5,43,10,0,0,7);ctx.fill();ctx.fillStyle=f.type.dark;ctx.fillRect(-27,-58,22,59);ctx.fillRect(5,-58,22,59);ctx.fillStyle='#111827';ctx.fillRect(-31,-9,28,12);ctx.fillRect(4,-9,29,12);ctx.fillStyle=f.flash>0?'#fff':f.type.color;ctx.beginPath();ctx.moveTo(-35,-132);ctx.lineTo(35,-132);ctx.lineTo(27,-56);ctx.lineTo(-27,-56);ctx.closePath();ctx.fill();ctx.fillStyle=f.type.skin;ctx.fillRect(-24,-177,48,47);ctx.fillStyle=f.type.dark;ctx.fillRect(-26,-181,53,13);ctx.fillStyle='#1b2029';ctx.fillRect(9,-158,7,5);ctx.fillStyle=f.type.skin;ctx.fillRect(-43,-125,19,51);let punch=f.attack?f.attack==='light'?24:44:0;ctx.fillRect(25,-125,18+punch,45);ctx.fillStyle=f.type.dark;ctx.fillRect(-44,-82,21,19);ctx.fillRect(31+punch,-82,22,19);if(f.block){ctx.strokeStyle='#99dcff';ctx.lineWidth=5;ctx.beginPath();ctx.arc(0,-104,61,-1.4,1.3);ctx.stroke();}if(f.attack==='special'){ctx.strokeStyle='#ffe079';ctx.lineWidth=5;ctx.beginPath();ctx.arc(0,-105,58,0,6.3);ctx.stroke();}ctx.restore();}
function draw(){drawStage();drawFighter(p);drawFighter(e);for(const shot of projectiles){ctx.fillStyle=shot.color;ctx.shadowColor=shot.color;ctx.shadowBlur=24;ctx.beginPath();ctx.arc(shot.x,shot.y,20+Math.sin(clock*25)*4,0,7);ctx.fill();ctx.shadowBlur=0;}for(const fx of effects){ctx.globalAlpha=Math.min(1,fx.life*3);ctx.fillStyle=fx.color;ctx.fillRect(fx.x,fx.y,6,6);}ctx.globalAlpha=1;}
function frame(now){let dt=Math.min(.04,(now-last)/1000||0);last=now;update(dt);draw();requestAnimationFrame(frame);}draw();requestAnimationFrame(frame);
})();